import React, { useState } from 'react'
import styles from '../styles/RegistrationForm.module.scss'
import { MdKeyboardArrowDown, MdKeyboardArrowUp, MdKeyboardArrowRight } from 'react-icons/md'
import Head from 'next/head'
import { FaRegHandshake, FaProjectDiagram } from 'react-icons/fa'
import { AiTwotoneCalendar, AiOutlineSetting } from 'react-icons/ai'
import Topbar from '../Component/Topbar'
import Navbar from '../Component/Navbar'
import Footer from '../Component/Footer'
import Popup from '../Component/Popup'


function RegistrationForm() {

  const [show, setShow] = useState(false);

  return (
    <>

      <Head>
        <title>Contact us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* ---------------font----------------------------> */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link href="https://fonts.googleapis.com/css2?family=Charis+SIL:wght@700&family=Roboto:wght@300&family=Source+Sans+Pro&display=swap" rel="stylesheet" />
      </Head>

      <Topbar />

      <Navbar />


      <div className={styles.enrollment}>
        <div className={styles.enrollmentContainer}>
          <div className={styles.text}>
            <div className={styles.badge}>
              <h3>Certified Online Training</h3>
            </div>

            <h1>Get Trained , Get Placed</h1>

            <h3>With <span className={styles.white}> India&apos;s No.1 </span> </h3>
            <h3>Embedded Training Institute </h3>

            <p>
              <div className={styles.span} > <FaRegHandshake className={styles.placementicon} /> Placement Assistance</div>
              <div className={styles.span}> <FaProjectDiagram className={styles.projecticon} /> Live Projects</div>

            </p>

            <p>
              <div className={styles.span}> <AiOutlineSetting className={styles.techicon} /> Technical Support</div>
              <div className={styles.span}> <AiTwotoneCalendar className={styles.durationicon} />Flexible Schedule </div>
            </p>

          </div>

        
    
<div className={styles.form}>
    <Popup />
</div>

      

        </div>
      </div>

      <Footer/>

    </>
  )
}

export default RegistrationForm